Ui prototypes
htw-exam-planner/exam-planer-requirements pull request #2
Opened 2018-05-15 09:26 UTC by DevWurm

2018-05-15 16:34 UTC, fbkr approved these changes

2018-05-15 18:51 UTC, revilovs requested changes
Kannst du die bitte alle ins Pflichtenheft einfügen?

2018-05-15 20:53 UTC, revilovs commented
Die Bilder Date management Admin (Edit Button pressed, Deactivated).png und Date management Admin (Edit Button pressed, no Booking).png und Date management Admin (Edit Button pressed, Reservation present).png sind alle 3 identisch, stellen alle letzteren Fall dar

2018-05-15 20:54 UTC, revilovs commented
Es fehlen außerdem die Felder um die Bemerkung zu bearbeiten

2018-05-16 08:58 UTC, revilovs requested changes
2 Kleinigkeiten, ansonsten super

2018-05-16 08:58 UTC, revilovs commented on Pflichtenheft.md
> +Nach dem Drücken des "Buchen" Knopfes muss der Student die Startzeit für die Proüfung eingeben.
Typo: Proüfung

2018-05-16 08:58 UTC, revilovs commented on Pflichtenheft.md
> +![Termin bearbeiten - Reservierung](ui-prototypes/exports/Date%20management%20Admin%20\(Edit%20Button%20pressed,%Reservation%20present\).png)
Hier stimmt was mit dem Filename nicht, wird nicht angezeigt

2018-05-16 11:24 UTC, revilovs approved these changes

2018-05-16 11:24 UTC, merged