initaler Release des Grobentwurfes
htw-exam-planner/exam-planer-requirements pull request #5
Opened 2018-05-19 16:41 UTC by denisk176

Ich habe mir mal Gedanken zum Grobentwurf gemacht. Bitte schaut einmal drüber und gebt Hinweise wo ich evtl. was vergessen haben könnte bzw. was noch fehlt. 

Für die Erstellung bin ich nach unseren Vorlesungsfolien gegangen. 

Danke

2018-05-20 09:43 UTC, DevWurm requested changes
An welchen Standard lehnst du dich hier an?
Die Dinge die hier beschrieben sind sind eher Teil der Anforderungsanalyse (damit Pflichenheft) und nicht des Entwurfs

2018-05-20 09:43 UTC, DevWurm commented on Grobentwurf.md
> +Der Client soll mit einer Schnittstelle zur Datenbank und zum Exportieren der gesammelten Daten in eine PDF-Datei ausgestattet werden. Weiterhin nimmt er Eingaben der Gruppen und Administratoren entg
Der Export ist nur optional, da würde ich mich nicht drauf festlegen

2018-05-21 08:44 UTC, revilovs requested changes
Sehe ich wie @DevWurm, hier gehört nicht das gleiche rein wie ins Pflichtenheft, sondern hier insbesondere die Paketdiagramme. Entwurf ist das, was wir die letzten Wochen in den SE-Praktika gemacht haben

2018-05-25 08:00 UTC, revilovs commented
Entwurf wird im documentation-Repo gemacht

2018-05-25 08:00 UTC, closed without merging