initaler Release Feinentwurf
htw-exam-planner/exam-planer-requirements pull request #6
Opened 2018-05-19 17:18 UTC by denisk176

Hier ist mein bisheriger Stand zum Feinentwurf. 

Schaut bitte mal drüber .

2018-05-20 09:45 UTC, DevWurm requested changes
Trifft teilweise nicht den Inhalt des Entwurfes

2018-05-20 09:45 UTC, DevWurm commented on Feinentwurf.md
> +## 2.2 Qualitätsanforderungen an den Quellcode
Eher teil der QA nicht des Entwurfs

2018-05-20 09:45 UTC, DevWurm commented on Feinentwurf.md
> +## 2.3 funktionale Anforderungen
Steht schon im Pflichenheft, gehört hier glaub ich eher weniger hin

2018-05-20 11:51 UTC, denisk176 commented on Feinentwurf.md
> +## 2.2 Qualitätsanforderungen an den Quellcode
Ich glaube, man sollte es zumindest mal erwähnen. Aber ich kann es auch gerne raus nehmen.

2018-05-21 08:38 UTC, revilovs commented on Feinentwurf.md
> +## 2.2 Qualitätsanforderungen an den Quellcode
Ja, das sind die QA, das kommt bei der Dokumentation unter den QA rein, nicht hier

2018-05-21 08:41 UTC, revilovs requested changes
Das ist soweit ich sehe nicht wirklich ein Feinentwurf. Der Feinentwurf besteht vor allem aus den Klassendiagrammen und dergleichen, also welche Klasse hat was für Felder und Methoden und so

2018-05-25 08:00 UTC, revilovs commented
Entwurf wir im documentation-Repo gemacht

2018-05-25 08:00 UTC, closed without merging